# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1440, 786)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(230, 190, 641, 411))
        self.tabWidget.setToolTipDuration(0)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(190, 110, 261, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(190, 150, 271, 16))
        self.label_2.setObjectName("label_2")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(40, 40, 551, 311))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(self.verticalLayoutWidget_3)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 547, 307))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.animal_list = QtWidgets.QListWidget(self.scrollAreaWidgetContents)
        self.animal_list.setGeometry(QtCore.QRect(0, 0, 541, 301))
        self.animal_list.setObjectName("animal_list")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(50, 20, 121, 16))
        self.label_3.setObjectName("label_3")
        self.bt_add_animal = QtWidgets.QToolButton(self.tab_2)
        self.bt_add_animal.setGeometry(QtCore.QRect(480, 10, 41, 22))
        self.bt_add_animal.setObjectName("bt_add_animal")
        self.bt_remove_animal = QtWidgets.QToolButton(self.tab_2)
        self.bt_remove_animal.setGeometry(QtCore.QRect(530, 10, 51, 22))
        self.bt_remove_animal.setObjectName("bt_remove_animal")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.bt_add_enclosure = QtWidgets.QToolButton(self.tab_3)
        self.bt_add_enclosure.setGeometry(QtCore.QRect(480, 10, 41, 22))
        self.bt_add_enclosure.setObjectName("bt_add_enclosure")
        self.bt_remove_enclosure = QtWidgets.QToolButton(self.tab_3)
        self.bt_remove_enclosure.setGeometry(QtCore.QRect(530, 10, 51, 22))
        self.bt_remove_enclosure.setObjectName("bt_remove_enclosure")
        self.label_5 = QtWidgets.QLabel(self.tab_3)
        self.label_5.setGeometry(QtCore.QRect(50, 20, 71, 16))
        self.label_5.setObjectName("label_5")
        self.enclosure_list = QtWidgets.QListWidget(self.tab_3)
        self.enclosure_list.setGeometry(QtCore.QRect(50, 50, 531, 311))
        self.enclosure_list.setObjectName("enclosure_list")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1440, 22))
        self.menubar.setObjectName("menubar")
        self.menuFs = QtWidgets.QMenu(self.menubar)
        self.menuFs.setObjectName("menuFs")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFs.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Welcome to Zoo Management, Zookeeper! "))
        self.label_2.setText(_translate("MainWindow", "Click one of the tabs above to get started."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Welcome"))
        self.label_3.setText(_translate("MainWindow", "Animals"))
        self.bt_add_animal.setText(_translate("MainWindow", "Add"))
        self.bt_remove_animal.setText(_translate("MainWindow", "Remove"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Animals"))
        self.bt_add_enclosure.setText(_translate("MainWindow", "Add"))
        self.bt_remove_enclosure.setText(_translate("MainWindow", "Remove"))
        self.label_5.setText(_translate("MainWindow", "Enclosures"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Enclosures"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Settings"))
        self.menuFs.setTitle(_translate("MainWindow", "Main Menu"))

